:- style_check(-discontiguous).
kind("services","religion").
kind("offered","religion").
kind("offered","finance").
kind("a","health").
kind("support","politics").
kind("south","geography").
kind("ridge","geography").
kind("following","demographic").
kind("fitness","health").
kind("youth","demographic").
kind("rentals","finance").
kind("offer","religion").
kind("offer","finance").
kind("adults","demographic").
kind("families","demographic").
kind("free","finance").
kind("family","demographic").
kind("members","politics").
kind("members","demographic").
kind("have","demographic").
kind("loved","demographic").
kind("disorder","health").
kind("programs","finance").
kind("as","geography").
kind("as","health").
kind("funding","finance").
kind("local","health").
kind("organizations","politics").
kind("organizations","finance").
kind("help","demographic").
kind("people","politics").
kind("people","demographic").
kind("in","geography").
kind("more","politics").
kind("physicians","health").
kind("nurses","health").
kind("nurses","demographic").
kind("health","health").
kind("professionals","demographic").
kind("pharmacists","health").
kind("therapists","health").
kind("others","finance").
kind("treatment","health").
kind("conditions","finance").
kind("specialists","health").
kind("brothers","demographic").
kind("sisters","demographic").
kind("service","religion").
kind("children","demographic").
kind("facing","demographic").
kind("matching","demographic").
kind("volunteers","demographic").
kind("environment","geography").
kind("immigrant","demographic").
kind("enriching","finance").
kind("appropriate","finance").
kind("build","demographic").
kind("canada","geography").
kind("affordable","finance").
kind("homes","finance").
kind("homes","demographic").
kind("alberta","geography").
kind("aboriginal","geography").
kind("peoples","politics").
kind("peoples","demographic").
kind("can","finance").
kind("appointment","demographic").
kind("centre","geography").
kind("individuals","demographic").
kind("therapy","health").
kind("court","politics").
kind("crisis","finance").
kind("education","politics").
kind("needs","finance").
kind("individual","demographic").
kind("other","finance").
kind("city","geography").
kind("disabled","health").
kind("public","demographic").
kind("clients","demographic").
kind("hiv","health").
kind("program","finance").
kind("well","finance").
kind("providers","demographic").
kind("toll","finance").
kind("line","finance").
kind("meeting","geography").
kind("christmas","religion").
kind("light","religion").
kind("light","demographic").
kind("community","religion").
kind("community","finance").
kind("partners","demographic").
kind("kids","demographic").
kind("packs","health").
kind("peanut","demographic").
kind("hope","religion").
kind("disabilities","health").
kind("foundation","finance").
kind("subsidized","finance").
kind("rental","finance").
kind("afford","finance").
kind("sector","finance").
kind("contribute","finance").
kind("friend","religion").
kind("friend","politics").
kind("friend","demographic").
kind("intimate","demographic").
kind("partner","demographic").
kind("homelessness","demographic").
kind("term","finance").
kind("women","demographic").
kind("transition","religion").
kind("programming","finance").
kind("case","demographic").
kind("manager","finance").
kind("primary","politics").
kind("patients","health").
kind("men","demographic").
kind("men","geography").
kind("men","finance").
kind("homeless","demographic").
kind("haven","geography").
kind("young","religion").
kind("young","politics").
kind("supportive","politics").
kind("home","demographic").
kind("home","finance").
kind("begin","politics").
kind("heal","health").
kind("adult","demographic").
kind("self-sufficiency","politics").
kind("house","religion").
kind("house","politics").
kind("house","demographic").
kind("supports","politics").
kind("street","geography").
kind("healing","health").
kind("healthy","health").
kind("making","finance").
kind("credit","finance").
kind("counsellors","demographic").
kind("helps","demographic").
kind("based","geography").
kind("based","health").
kind("based","politics").
kind("based","finance").
kind("aides","demographic").
kind("lpn","health").
kind("supervisor","demographic").
kind("residents","geography").
kind("residents","health").
kind("facilities","finance").
kind("graham","religion").
kind("creek","geography").
kind("association","finance").
kind("domestic","demographic").
kind("debt","finance").
kind("relief","demographic").
kind("assessment","demographic").
kind("mandated","politics").
kind("receive","religion").
kind("relapse","health").
kind("feeling","health").
kind("centres","geography").
kind("independent","politics").
kind("independent","demographic").
kind("child","demographic").
kind("bonding","politics").
kind("attachment","politics").
kind("cost","finance").
kind("lots","religion").
kind("disease","health").
kind("dementias","health").
kind("caregivers","health").
kind("caregivers","demographic").
kind("disability","health").
kind("savings","religion").
kind("savings","finance").
kind("understanding","finance").
kind("newcomers","demographic").
kind("english","geography").
kind("english","politics").
kind("employment","finance").
kind("canadian","geography").
kind("red","geography").
kind("red","politics").
kind("ministry","politics").
kind("areas","geography").
kind("intervention","politics").
kind("sharing","finance").
kind("forms","demographic").
kind("sponsorship","politics").
kind("victims","demographic").
kind("area","geography").
kind("victim","demographic").
kind("voice","demographic").
kind("crown","politics").
kind("crown","demographic").
kind("patient","health").
kind("discharge","finance").
kind("business","finance").
kind("employability","finance").
kind("peer","demographic").
kind("connect","politics").
kind("peers","demographic").
kind("participants","demographic").
kind("improved","health").
kind("balance","finance").
kind("control","politics").
kind("control","finance").
kind("competitive","finance").
kind("contributes","finance").
kind("successful","demographic").
kind("clinicians","demographic").
kind("mosaic","health").
kind("mosaic","religion").
kind("mobile","geography").
kind("clinic","health").
kind("wellness","health").
kind("wellness","finance").
kind("calgary","geography").
kind("communities","religion").
kind("communities","finance").
kind("need","finance").
kind("cleaning","religion").
kind("cleaning","finance").
kind("oriented","geography").
kind("enrolled","finance").
kind("moms","demographic").
kind("al","geography").
kind("strength","finance").
kind("friends","religion").
kind("friends","politics").
kind("friends","demographic").
kind("drinkers","demographic").
kind("advocacy","politics").
kind("funds","finance").
kind("assurance","geography").
kind("organization","politics").
kind("organization","finance").
kind("helping","demographic").
kind("building","demographic").
kind("partnerships","finance").
kind("tenants","geography").
kind("tenants","finance").
kind("security","finance").
kind("down","geography").
kind("down","health").
kind("down","finance").
kind("roots","politics").
kind("rent","finance").
kind("government","politics").
kind("charge","finance").
kind("share","finance").
kind("agreements","finance").
kind("spiritual","religion").
kind("booking","religion").
kind("booking","finance").
kind("enrolment","finance").
kind("diet","health").
kind("diet","politics").
kind("diet","religion").
kind("respite","finance").
kind("seniors","demographic").
kind("connections","politics").
kind("connections","demographic").
kind("religiously","religion").
kind("personal","demographic").
kind("growth","health").
kind("make","finance").
kind("positive","health").
kind("nations","politics").
kind("inuit","geography").
kind("comfortable","finance").
kind("hospital","health").
kind("indigenous","geography").
kind("issues","finance").
kind("co","demographic").
kind("tools","demographic").
kind("success","demographic").
kind("person","demographic").
kind("feel","health").
kind("selection","religion").
kind("current","geography").
kind("high","finance").
kind("interest","finance").
kind("material","demographic").
kind("possible","demographic").
kind("surrounding","geography").
kind("makes","finance").
kind("effective","health").
kind("discharges","finance").
kind("acute","health").
kind("managers","finance").
kind("churches","religion").
kind("christian","religion").
kind("u.s.","geography").
kind("u.s.","politics").
kind("mission","religion").
kind("mission","politics").
kind("girls","demographic").
kind("jesus","religion").
kind("christ","religion").
kind("christ","demographic").
kind("worship","religion").
kind("ministerial","religion").
kind("transients","demographic").
kind("transportation","politics").
kind("transportation","finance").
kind("persons","demographic").
kind("town","geography").
kind("county","geography").
kind("financial","finance").
kind("type","demographic").
kind("break","health").
kind("break","finance").
kind("paid","finance").
kind("retirement","religion").
kind("nursing","health").
kind("assured","geography").
kind("peace","politics").
kind("financing","finance").
kind("scouts","demographic").
kind("guides","demographic").
kind("valley","geography").
kind("gets","health").
kind("gets","finance").
kind("points","geography").
kind("west","geography").
kind("allowing","finance").
kind("favorites","demographic").
kind("familiar","demographic").
kind("settlement","geography").
kind("settlement","politics").
kind("orientation","geography").
kind("client","demographic").
kind("settling","politics").
kind("settling","finance").
kind("clinics","health").
kind("complimentary","finance").
kind("bank","geography").
kind("bank","finance").
kind("drugs","health").
kind("substances","finance").
kind("change","geography").
kind("independently","politics").
kind("changes","geography").
kind("general","health").
kind("response","religion").
kind("infections","health").
kind("parents","demographic").
kind("currently","geography").
kind("currently","finance").
kind("north","geography").
kind("north","politics").
kind("saskatchewan","geography").
kind("river","geography").
kind("offers","religion").
kind("offers","finance").
kind("geriatric","health").
kind("needed","finance").
kind("doctor","health").
kind("doctor","religion").
kind("medication","health").
kind("administration","health").
kind("administration","politics").
kind("administration","finance").
kind("injection","health").
kind("monitoring","demographic").
kind("illness","health").
kind("allows","finance").
kind("focus","health").
kind("important","demographic").
kind("eye","demographic").
kind("soup","health").
kind("clearly","finance").
kind("medications","health").
kind("indicate","health").
kind("taken","health").
kind("taken","finance").
kind("taking","health").
kind("taking","finance").
kind("easy","finance").
kind("call","finance").
kind("ms","geography").
kind("ms","health").
kind("better","health").
kind("better","religion").
kind("better","finance").
kind("department","geography").
kind("additional","finance").
kind("properties","finance").
kind("leased","geography").
kind("leased","finance").
kind("rented","finance").
kind("job","religion").
kind("job","demographic").
kind("cover","politics").
kind("cover","finance").
kind("defence","health").
kind("defence","politics").
kind("office","religion").
kind("office","politics").
kind("justice","politics").
kind("edmonton","geography").
kind("parkinson","health").
kind("learners","demographic").
kind("called","finance").
kind("newborns","demographic").
kind("targeted","demographic").
kind("volunteer","demographic").
kind("survivor","demographic").
kind("counsellor","demographic").
kind("explore","health").
kind("caregiver","health").
kind("caregiver","demographic").
kind("acceptance","politics").
kind("suffering","health").
kind("chronic","health").
kind("progressive","politics").
kind("employers","finance").
kind("employers","demographic").
kind("transferees","demographic").
kind("transferees","finance").
kind("subjects","politics").
kind("ask","finance").
kind("race","politics").
kind("religion","religion").
kind("doctors","health").
kind("doctors","religion").
kind("psychiatrists","health").
kind("outpatient","health").
kind("clinical","health").
kind("face","demographic").
kind("text","religion").
kind("medical","health").
kind("injury","health").
kind("trauma","health").
kind("witnesses","demographic").
kind("co-workers","demographic").
kind("wants","finance").
kind("regular","politics").
kind("regular","demographic").
kind("physician","health").
kind("member","politics").
kind("member","demographic").
kind("senior","demographic").
kind("human","demographic").
kind("pm","demographic").
kind("want","finance").
kind("anger","religion").
kind("controlling","politics").
kind("controlling","finance").
kind("citizens","politics").
kind("forming","demographic").
kind("less","health").
kind("ambrose","religion").
kind("works","religion").
kind("fit","health").
kind("documents","finance").
kind("filing","finance").
kind("books","religion").
kind("books","finance").
kind("materials","demographic").
kind("economical","finance").
kind("political","politics").
kind("adolescents","demographic").
kind("male","geography").
kind("welfare","finance").
kind("independence","geography").
kind("independence","politics").
kind("mother","demographic").
kind("made","finance").
kind("benefit","finance").
kind("pension","finance").
kind("severely","finance").
kind("handicapped","health").
kind("babies","demographic").
kind("parenting","demographic").
kind("western","geography").
kind("psychiatric","health").
kind("stabilization","politics").
kind("neurosurgeon","health").
kind("diseases","health").
kind("punjabi","geography").
kind("hindi","religion").
kind("bleeding","health").
kind("bleeding","finance").
kind("cell","religion").
kind("cell","politics").
kind("h","geography").
kind("hemoglobinuria","health").
kind("transfusion","health").
kind("dependent","finance").
kind("failure","demographic").
kind("failure","health").
kind("failure","finance").
kind("syndromes","health").
kind("province","geography").
kind("assessments","demographic").
kind("rehabilitation","health").
kind("surgery","health").
kind("oncological","health").
kind("pain","health").
kind("pain","demographic").
kind("interventions","politics").
kind("get","health").
kind("get","finance").
kind("shopping","finance").
kind("cancer","health").
kind("drug","health").
kind("allow","finance").
kind("conditioner","finance").
kind("orders","religion").
kind("orders","politics").
kind("contacted","demographic").
kind("refunds","finance").
kind("operations","finance").
kind("administered","health").
kind("assumption","religion").
kind("experts","demographic").
kind("aids","health").
kind("due","finance").
kind("fire","finance").
kind("flood","geography").
kind("hospitalization","health").
kind("moral","religion").
kind("amputees","demographic").
kind("involvement","politics").
kind("specialist","health").
kind("frailty","health").
kind("functional","health").
kind("decline","geography").
kind("decline","health").
kind("decline","finance").
kind("impairment","health").
kind("dementia","health").
kind("falls","geography").
kind("falls","religion").
kind("assessed","demographic").
kind("specific","health").
kind("chapters","religion").
kind("miracles","religion").
kind("dog","demographic").
kind("movement","politics").
kind("dependency","geography").
kind("documentation","finance").
kind("milk","geography").
kind("means","finance").
kind("stroke","demographic").
kind("survivors","demographic").
kind("socialization","politics").
kind("shared","finance").
kind("roommate","demographic").
kind("receiving","religion").
kind("best","demographic").
kind("best","finance").
kind("resident","geography").
kind("resident","health").
kind("offering","religion").
kind("offering","finance").
kind("modern","demographic").
kind("hospice","health").
kind("beginning","politics").
kind("comfort","finance").
kind("someone","demographic").
kind("use","finance").
kind("workers","demographic").
kind("institutions","health").
kind("pastoral","religion").
kind("confession","religion").
kind("connection","politics").
kind("connection","demographic").
kind("newcomer","demographic").
kind("specialized","finance").
kind("documented","finance").
kind("companion","demographic").
kind("autism","health").
kind("schizophrenia","health").
kind("interpreters","demographic").
kind("interpreters","finance").
kind("appointments","demographic").
kind("interpreter","demographic").
kind("interpreter","finance").
kind("therapist","health").
kind("using","finance").
kind("harm","health").
kind("model","demographic").
kind("paediatrician","health").
kind("exit","health").
kind("exiting","health").
kind("assesment","demographic").
kind("cities","geography").
kind("advanced","finance").
kind("treat","health").
kind("connected","politics").
kind("environments","geography").
kind("multitude","politics").
kind("addictions","demographic").
kind("publicly","demographic").
kind("insured","politics").
kind("condition","finance").
kind("wanting","finance").
kind("officers","demographic").
kind("prospective","health").
kind("prospective","politics").
kind("bursary","finance").
kind("focused","health").
kind("sclerosis","health").
kind("offices","religion").
kind("offices","politics").
kind("inpatient","health").
kind("endoscopy","health").
kind("gastroscopy","health").
kind("portion","finance").
kind("lewis","politics").
kind("estates","politics").
kind("estates","finance").
kind("features","demographic").
kind("commitment","finance").
kind("pediatric","health").
kind("gynecological","health").
kind("does","politics").
kind("conservative","politics").
kind("majority","politics").
kind("supported","politics").
kind("realize","finance").
kind("facility","finance").
kind("benefits","finance").
kind("indicated","health").
kind("fee","finance").
kind("located","politics").
kind("maintenance","finance").
kind("cutting","health").
kind("cutting","religion").
kind("cutting","finance").
kind("removal","finance").
kind("moderate","politics").
kind("surgical","health").
kind("infants","demographic").
kind("neighbors","demographic").
kind("prairie","geography").
kind("ab","health").
kind("calling","finance").
kind("operator","demographic").
kind("names","health").
kind("names","demographic").
kind("contact","demographic").
kind("numbers","religion").
kind("boys","demographic").
kind("professional","demographic").
kind("partnership","finance").
kind("seed","health").
kind("seed","finance").
kind("ministries","politics").
kind("oasis","geography").
kind("pentecostal","religion").
kind("church","religion").
kind("venture","finance").
kind("clinically","health").
kind("spending","finance").
kind("natural","demographic").
kind("makers","finance").
kind("makers","demographic").
kind("cases","demographic").
kind("close","finance").
kind("pip","health").
kind("smarts","health").
kind("rural","geography").
kind("recently","finance").
kind("released","finance").
kind("study","religion").
kind("injuries","health").
kind("real","finance").
kind("lake","geography").
kind("medicine","health").
kind("poverty","finance").
kind("moving","politics").
kind("moving","finance").
kind("giving","health").
kind("giving","finance").
kind("equality","demographic").
kind("deaf","health").
kind("engaged","finance").
kind("spirit","religion").
kind("order","religion").
kind("order","politics").
kind("banff","geography").
kind("orthopedic","health").
kind("podiatry","health").
kind("visitors","demographic").
kind("world","demographic").
kind("point","geography").
kind("source","demographic").
kind("northeast","geography").
kind("elder","religion").
kind("elder","demographic").
kind("friendly","religion").
kind("friendly","politics").
kind("friendly","demographic").
kind("combination","finance").
kind("aide","demographic").
kind("extra","finance").
kind("inclusion","health").
kind("parent","demographic").
kind("viewing","religion").
kind("document","finance").
kind("shoppers","demographic").
kind("discount","finance").
kind("priced","finance").
kind("addiction","demographic").
kind("participation","politics").
kind("recover","health").
kind("tax","politics").
kind("advocates","demographic").
kind("assess","geography").
kind("assess","demographic").
kind("productive","finance").
kind("focuses","health").
kind("traumatic","health").
kind("habitat","geography").
kind("humanity","demographic").
kind("give","health").
kind("give","finance").
kind("rights","finance").
kind("rights","politics").
kind("rights","demographic").
kind("dressing","health").
kind("gives","health").
kind("gives","finance").
kind("consideration","finance").
kind("values","religion").
kind("values","finance").
kind("chinese","geography").
kind("balanced","finance").
kind("nurse","health").
kind("nurse","demographic").
kind("centered","politics").
kind("engagement","politics").
kind("engagement","finance").
kind("strengths","finance").
kind("therapeutic","health").
kind("name","health").
kind("name","demographic").
kind("houses","religion").
kind("houses","politics").
kind("houses","demographic").
kind("highly","finance").
kind("types","demographic").
kind("kin","demographic").
kind("worker","demographic").
kind("state","geography").
kind("state","politics").
kind("fleet","finance").
kind("charter","finance").
kind("field","geography").
kind("charters","finance").
kind("firefighter","politics").
kind("firefighter","demographic").
kind("drop","health").
kind("drop","finance").
kind("connecting","politics").
kind("back","politics").
kind("back","finance").
kind("volunteerism","demographic").
kind("active","health").
kind("socialize","politics").
kind("samaritan","demographic").
kind("congregation","religion").
kind("fast","health").
kind("fast","religion").
kind("medically","health").
kind("baby","demographic").
kind("lease","geography").
kind("lease","finance").
kind("comforts","finance").
kind("ideal","demographic").
kind("country","geography").
kind("country","politics").
kind("manor","finance").
kind("bathing","geography").
kind("bathing","religion").
kind("blind","health").
kind("buy","finance").
kind("shop","finance").
kind("gain","finance").
kind("beaumont","geography").
kind("beaumont","health").
kind("devon","geography").
kind("towns","geography").
kind("chronically","health").
kind("ill","health").
kind("youths","demographic").
kind("studies","religion").
kind("neighbours","demographic").
kind("la","geography").
kind("personalized","demographic").
kind("closely","finance").
kind("labor","politics").
kind("labor","finance").
kind("relaxation","finance").
kind("infant","demographic").
kind("disorders","health").
kind("take","health").
kind("take","finance").
kind("exploration","geography").
kind("centers","politics").
kind("crew","finance").
kind("engage","finance").
kind("reading","geography").
kind("budgeting","finance").
kind("media","geography").
kind("drinks","geography").
kind("drinks","health").
kind("dealing","finance").
kind("replacement","demographic").
kind("weekdays","finance").
kind("market","finance").
kind("representation","politics").
kind("muslim","religion").
kind("bookings","religion").
kind("bookings","finance").
kind("mon","religion").
kind("protective","politics").
kind("protective","finance").
kind("factors","finance").
kind("transitions","religion").
kind("psychiatrist","health").
kind("callers","demographic").
kind("bankruptcy","finance").
kind("budgets","finance").
kind("finances","finance").
kind("mediums","geography").
kind("song","finance").
kind("songs","finance").
kind("tips","finance").
kind("redeemer","religion").
kind("redeemer","finance").
kind("catholic","religion").
kind("brooks","geography").
